# Configurações de análise estática para o projeto Cicatriza
# Focado em Clean Architecture e qualidade de código

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Style and formatting
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    
    # Code organization
    always_put_required_named_parameters_first: true
    always_declare_return_types: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    
    # Clean Architecture principles
    depend_on_referenced_packages: true
    avoid_relative_lib_imports: true
    
    # Documentation
    public_member_api_docs: false # Desabilitado temporariamente
    lines_longer_than_80_chars: false # Flexível para readability
    
    # Error prevention
    avoid_print: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_empty_else: true
    
    # Performance
    prefer_collection_literals: true
    prefer_spread_collections: true
    avoid_function_literals_in_foreach_calls: true
    
    # Security
    avoid_web_libraries_in_flutter: true
    
    # Modern Dart
    prefer_null_aware_operators: true
    unnecessary_null_checks: true
    use_super_parameters: true
